# Generated by Django 4.0.6 on 2023-01-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_owner_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='OTP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='owner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
