# Generated by Django 4.1.7 on 2023-02-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0003_owner_otp_alter_owner_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="phone",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="owner",
            name="username",
            field=models.CharField(max_length=60),
        ),
    ]
