# Generated by Django 4.1.7 on 2023-02-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0004_alter_owner_phone_alter_owner_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="is_verfied",
            field=models.BooleanField(default=False),
        ),
    ]
