# Generated by Django 4.1.7 on 2023-08-17 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0005_owner_is_verfied"),
    ]

    operations = [
        migrations.RenameField(
            model_name="owner",
            old_name="is_verfied",
            new_name="confirmed",
        ),
        migrations.AddField(
            model_name="owner",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
