# Generated by Django 4.0.6 on 2023-01-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='location',
        ),
    ]
