# Generated by Django 4.1.7 on 2023-08-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0003_alter_house_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="status",
            field=models.CharField(default="rent", max_length=64, null=True),
        ),
    ]
